name: Update README with recent activity

on:
  schedule:
    - cron: "0 * * * *"  # Exécuter toutes les heures
  workflow_dispatch:     # Permet d'exécuter manuellement le workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: GitHub - Activity - Readme
        uses: jamesgeorge007/github-activity-readme@v0.4.4
        with:
          COMMIT_MSG: "Updated README with recent activity"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

